export const cardsFriendsData = [
    {
      id: 1,
      avatar: "avatar3.jpg",
      avatarAlt: "avatar",
      statusIcon: "offline.svg",
      statusText: "offline",
      title: "Urmu",
      description: "This is user one's descriptionfd",
      background: "background.png",
    },
    {
      id: 2,
      avatar: "avatar4.jpg",
      avatarAlt: "User Avatar 2",
      statusIcon: "offline.svg",
      statusText: "Offline",
      title: "Kitty",
      description: "Kitty's description goes here",
      background: "background.png",
    },
    {
      id: 3,
      avatar: "avatar2.png",
      avatarAlt: "User Avatar 3",
      statusIcon: "offline.svg",
      statusText: "offline",
      title: "User Three",
      description: "User three's description goes here",
      background: "background.png",
    },
    {
      id: 4,
      avatar: "avatar2.png",
      avatarAlt: "User Avatar 3",
      statusIcon: "offline.svg",
      statusText: "offline",
      title: "User Three",
      description: "User three's description goes here",
      background: "background.png",
    },
  ];
  